### ISSUE TITLE
Semana 4 (L24-V31)

### ISSUE THREAD

**Issue by dcardenasl** [oultrox/SistemaSushi#2]
- [x] Programar sistema de registro y login de usuarios. - @oultrox 
- [x] Programar control de acceso por nivel de usuario. @dcardenasl
- [x] Investigar implementación de API de correo. @oultrox 
- [x] Crear mantenedores de todas las tablas @Ryunagatk 
- [x] Crear vistas de ingreso de datos de todas las tablas @Ryunagatk 
- [x] Crear los Sesion beans @oultrox

**Comment by oultrox** [comment]
https://github.com/gcorreageek/blog <- Ejemplo de confirmación de correo
