### ISSUE TITLE
Semana 5 (L02-V07)

### ISSUE THREAD

**Issue by dcardenasl** [oultrox/SistemaSushi#3]
- [x] Estudiar implementación de API de pago externo. (WebPay) @Ryunagatk
- [x] Crear sistema de carro de compras @oultrox 
- [x] Crear sistema de control de compras para el cajero online @dcardenasl 
- [x] Crear sistema de envío de correo con boleta de @dcardenasl

**Comment by oultrox** [comment]
![image](https://cloud.githubusercontent.com/assets/10330846/24842792/966c9210-1d72-11e7-8433-eadb0ed17b10.png)

**Comment by oultrox** [comment]
![image](https://cloud.githubusercontent.com/assets/10330846/24842933/014372b0-1d74-11e7-95cd-590772c69964.png)
(Dejo a Carmen porque es bella.)

**Comment by oultrox** [comment]
![image](https://cloud.githubusercontent.com/assets/10330846/25069587/f1496e4a-225b-11e7-8fb2-e6464aabfe4a.png)

**Comment by oultrox** [comment]
![image](https://cloud.githubusercontent.com/assets/10330846/25069591/0977e5f0-225c-11e7-84f1-7afe067e5683.png)

**Comment by dcardenasl** [comment]
![msg enviado](https://cloud.githubusercontent.com/assets/12055196/25247636/bcbc78a0-25e1-11e7-83c8-b4cc6a649341.PNG)
